# Generated by Django 2.2.12 on 2020-08-13 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20200813_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='date_of_birth',
            new_name='DOB',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='info',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='info',
            name='user_name',
        ),
    ]
