# Generated by Django 2.2.12 on 2020-08-13 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student', '0003_auto_20200813_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(default='', max_length=100)),
                ('batch_n', models.IntegerField(default=0, max_length=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Student.info')),
            ],
        ),
    ]
